Repository scientific-python/specs, pull requests merged in 2024-09, with the labels that each got.

#339 Add publish state to SPEC process
  purpose-and-process/_index.md
Labels: Discuss in meeting

#336 ENH: add is-draft to the SPEC template and to the listed, but still WIP specs
  quickstart.py
  spec-0002/index.md
  spec-0003/index.md
  spec-0005/index.md
Labels: enhancement, Discuss in meeting

#323 Add SPEC9 - Governance
  spec-0009/index.md
Labels: New SPEC

#342 DOC: adding readme for .tools directory
  .tools/README
Labels: documentation
